name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21.0.3'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.0' # Match local Node.js version

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install JavaScript dependencies
      run: pnpm install

    - name: Install Java dependencies
      run: mvn install

    - name: Setup FFmpeg 7.0.1
      uses: federicocarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: '7.0.1'

    - name: Run Java tests
      run: mvn test

    - name: Display logs
      run: cat /home/runner/work/atmos-downmix/atmos-downmix/target/surefire-reports/*.txt

    - name: Run JavaScript tests
      run: pnpm test