name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install JavaScript dependencies
      run: pnpm install

    - name: Install Java dependencies
      run: mvn install

    - name: Run Java tests
      run: mvn test

    - name: Run JavaScript tests
      run: pnpm test